# Generated by Django 4.2 on 2024-11-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('skills', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='JobPosting',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='experience_years',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='skills',
            field=models.CharField(max_length=200),
        ),
    ]
