# Generated by Django 5.1.3 on 2024-11-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_recommendation', '0002_jobpost_delete_jobposting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
